name: krr
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - sqlite
  - spacy>=3.7,<4.0
  - tqdm
  - requests
  - pillow
  - pytorch>=2.0
  - torchvision
  - pip
  - pip:
      - transformers>=4.36
      - accelerate>=0.25
      - pytest>=7.0